// Fetching Data From the API
export const FETCH_CURRENCY_DATA_SUCCESS = 'FETCH_CURRENCY_DATA_SUCCESS';
export const FETCH_CURRENCY_DATA_FAIL = 'FETCH_CURRENCY_DATA_FAIL';

// Select an Item
export const GET_SELECTED_ITEM = "GET_SELECTED_ITEM";